### ISSUE TITLE
NRF24 transfer speed

### ISSUE THREAD

**Issue by Constructor-999** [nRF24/pyRF24#13]
Hello, I would like to know what is the transfer speed on nrf24 and if it is possible to change the size of the payload in the main loop ?

Thanks

**Comment by 2bndy5** [comment]
> transfer speed on nrf24

If you're talking about the OTA data rate, then [`RF24.data_rate`](https://pyrf24.readthedocs.io/en/latest/rf24_api.html#pyrf24.rf24.RF24.data_rate) will let you customize that (lib defaults to 1 Mbps).

If you're talking about the SPI baudrate used to drive the radio, then that can be optionally specified once in the [RF24 c'tor](https://pyrf24.readthedocs.io/en/latest/rf24_api.html#pyrf24.rf24.RF24.__init__).

> change the size of the payload

Yes, a quick look at our lib's [getting_started example](https://pyrf24.readthedocs.io/en/latest/examples.html#getting-started) would have told you that. Keep in mind that the radio has a dynamic payload size feature, but it is disabled by default. See [`RF24.payload_size`](https://pyrf24.readthedocs.io/en/latest/rf24_api.html#payload-sizes) for more detail.

**Comment by 2bndy5** [comment]
Lastly, the maximum payload size is 32 bytes (minimum is 1). This info seems to have been left out of the docs (& should be added).

Most of the pyrf24 pkg's docs are also accessible with the python REPL's builtin `help()` function.
```py
>>> import pyrf24
>>> help(pyrf24.RF24.payload_size)
```
