### ISSUE TITLE
is it reliable to use for TDD?

### ISSUE THREAD

**Issue by akash02ita** [nRF24/pyRF24#88]
I assume NRF24 modules are half duplex and not full duplex.
Is the library sustainable to use for TDD, where it be switching between rx/tx mode repeatedly?
is startlistening/stoplistening a very quick execution to swtich between rx/tx mode or it could be a bottleneck?

I wonder if you tested it in that type of scenario

**Comment by 2bndy5** [comment]
As developer, you will learn that it is never good to assume something without researching first. Just looking at the nRF24L01 datasheet would have told you that the SPI transactions are full duplex.

The code for this package is the C++ Arduino libraries (ported to work on Linux) RF24, RF24Network, and RF24Mesh. These libraries have been battle hardened over the last decade.

We actually have an example that quickly and repeatedly switches between RX and TX mode. Try out examples/manual_acknowledgements.py and see for yourself.

**Comment by 2bndy5** [comment]
I had to look up what TDD means. According to [Wikipedia](https://en.wikipedia.org/wiki/Test-driven_development),

> Test-driven development (TDD) is a way of writing [code](https://en.wikipedia.org/wiki/Source_code) that involves writing an [automated](https://en.wikipedia.org/wiki/Test_automation) [unit-level](https://en.wikipedia.org/wiki/Unit_testing) [test case](https://en.wikipedia.org/wiki/Test_case) that fails, then writing just enough code to make the test pass, then [refactoring](https://en.wikipedia.org/wiki/Refactoring) both the test code and the production code, then repeating with another new test case.

Honestly, this sounds like my typical development process. There's a rather common slogan in maker community: "break things" refers to this "TDD" approach in laymen terms. The idea is that you always start out with broken code, then learn to fix it...

I recently ported the C++ RF24 lib's algorithms to pure rust, and that is the first time I wrote code that succeeded on first try. Then I added code to intentionally produce errors (for unit testing). 🤣 I guess you just get better over time, but that `rustc` compiler leaves very little room for unintentional errors.

**Comment by akash02ita** [comment]
Great Thanks! By TDD i meant Time Division Duplexing.

"Just looking at the nRF24L01 datasheet would have told you that the SPI transactions are full duplex."  i did not quite understand this part.
Do you mean that SPI protocol allows to send and receive at same time through MISO/MOSI lines.. I get that they are full duplex in that part. But i was wondering about the actual nRF24L01 transceiver if that supports to be full duplex.

Looking up online I do find that nRF24L01 are half duplex, since for each one antenna is involved. So we can receive and transmit one at a time. While I could use different data pipe addresses out of the 6 available (for instance, for transceiver1 use '1node' as addresss to transmit and '2node' as address to receive; and for transceiver2 use '2node' as address to transmit and '1node' as address to receive; which this is pretty much what you examples code seem to do) it is not possible to use both address pipes to transmit and receive at the same time right?
If yes, that is where I thought I need to alternate between radio.listen = False/True.

But based on your feedback, i'll try out myself how fast I can switch between them.

**Comment by 2bndy5** [comment]
> But i was wondering about the actual nRF24L01 transceiver if that supports to be full duplex.

Oh, I see. The radio implements a flexible wireless protocol called "Enhanced ShockBurst" (ESB for short). If you enable the ACK payloads feature (see examples/acknowledgement_payloads.py), then the transceiver can _behave_ as full duplex OTA (Over The Air). By default, we configure the radio to _behave_ as half duplex OTA (for speed and convenience).

> [!note]
> There's no way for a single radio to be truly full duplex OTA. That would require something like a quantum circuit which AFAIK doesn't exist in the world of radios. The only way to achieve true full duplex OTA is to have 2 radio transceivers driven by a single node simultaneously, and that would require each node to be equipped with 2 transceivers.

In case you want a single radio to receive data from multiple transmitters, you should have a look at examples/multiceiver_demo.py to understand the best way to do that.

> And since I would be using different addresses, I wouldn't need to worry about collisions

Again, see examples/multiceiver_demo.py. Especially note how that example uses [`RF24.set_retries()`](https://pyrf24.readthedocs.io/en/latest/rf24_api.html#pyrf24.RF24.set_retries) because this is how the datasheet recommends avoiding collisions.

> it is not possible to use both address pipes to transmit and receive at the same time right?

No. Only pipe 0 can be used to transmit (including auto-ack packets during RX operations). Have a look at the datasheet's Appendix A for an in-depth explanation about how the auto-ack feature works.

> [!caution]
> Only pipes 0 & 1 can have a unique 5-byte address. Pipes 2 - 5 use 1 unique byte (MSB) with the 4 LSBs from the address set to pipe 1.
>
> Call [`RF24.print_pretty_details()`](https://pyrf24.readthedocs.io/en/latest/rf24_api.html#pyrf24.RF24.print_pretty_details) to see how the radio uses the addresses passed to [`open_rx_pipe()`](https://pyrf24.readthedocs.io/en/latest/rf24_api.html#pyrf24.RF24.open_rx_pipe) and [`open_tx_pipe()`](https://pyrf24.readthedocs.io/en/latest/rf24_api.html#pyrf24.RF24.open_tx_pipe).
